server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taotie?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
